on:
  workflow_dispatch:
  push:
  pull_request:
  schedule:
    - cron: '0 8 * * *'

name: 'CI / Latest SC'

defaults:
  run:
    shell: bash

env:
  REGISTRY: ghcr.io

jobs:
  docker_image:
    uses: siliconcompiler/siliconcompiler/.github/workflows/docker_image.yml@main
    with:
      tool: 'tools'

  flat:
    name: 'flat'
    needs: docker_image
    timeout-minutes: 180
    runs-on: ubuntu-latest
    container:
      image: ${{ needs.docker_image.outputs.sc_tool }}
      credentials:
        username: ${{ secrets.PACKAGES_ACTOR }}
        password: ${{ secrets.PACKAGES_TOKEN }}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: apt install python3-venv
      - name: Run test
        run: |
          git clone https://github.com/siliconcompiler/siliconcompiler /siliconcompiler
          python3 -m venv ./clean_env --clear
          source ./clean_env/bin/activate
          echo $VIRTUAL_ENV
          pip3 install -r python-requirements.txt
          pip3 install /siliconcompiler
          ./build.py --top-flat
        env:
          SCPATH: /siliconcompiler/siliconcompiler

      - name: Upload image artifacts
        uses: actions/upload-artifact@v3
        with:
          name: flat
          path: build/zerosoc/job0/zerosoc.png
          retention-days: 5

  hierarchical:
    name: 'hierarchical'
    needs: docker_image
    timeout-minutes: 180
    runs-on: ubuntu-latest
    container:
      image: ${{ needs.docker_image.outputs.sc_tool }}
      credentials:
        username: ${{ secrets.PACKAGES_ACTOR }}
        password: ${{ secrets.PACKAGES_TOKEN }}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: apt install python3-venv
      - name: Run test
        run: |
          git clone https://github.com/siliconcompiler/siliconcompiler /siliconcompiler
          python3 -m venv ./clean_env --clear
          source ./clean_env/bin/activate
          echo $VIRTUAL_ENV
          pip3 install -r python-requirements.txt
          pip3 install /siliconcompiler
          ./build.py --core-only
          ./build.py --top-only
        env:
          SCPATH: /siliconcompiler/siliconcompiler

      - name: Upload image artifacts
        uses: actions/upload-artifact@v3
        with:
          name: hierarchical
          path: |
            build/zerosoc_core/job0/zerosoc_core.png
            build/zerosoc_top/job0/zerosoc_top.png
          retention-days: 5
